### ISSUE TITLE
Module's package.json file may make trouble

### ISSUE THREAD

**Issue by luobotang** [less/less-plugin-npm-import#15]
I made a npm module, and it's `package.json` file has `main` property with value `index.js`. It's common thing, I think.
Also, the module has a `index.less` file, and with `less-plugin-npm-import`, I import it in another less file like this:

``` less
@import "npm://module_name";
```

I thought this is alse common thing. But, I can't pass the grunt.
From the error message, it says there's something wrong with `module_name/index.js` file!
![1](https://cloud.githubusercontent.com/assets/4198591/9266697/4951f3e4-4277-11e5-844c-3c57316a365a.png)

Before post a issue here directly, I try to find out why ... then, I think the answer may be here:

``` javascript
// node_modules/resolve/lib/async.js line147-151
                if (pkg.main) {
                    if (pkg.main === '.' || pkg.main === './'){
                        pkg.main = 'index'
                    }
                    loadAsFile(path.resolve(x, pkg.main), pkg, function (err, m, pkg) {
```

The resolve will try to load the main file defined in package.json file. So, as in my module's package.json, main is "index.js"...that's my fault?!

Maybe this is not the responsibility of `less-plugin-npm-import`. If so, I just share my solution here:
**Change the "main" property's value from "index.js" to "index"!**

PS: thanks for published `less-plugin-npm-import`, it's very useful!

**Comment by gitdust** [comment]
@luobotang I had a problem like yours.I have installed `less-plugin-npm-import` in global and in my LESS file I import this module just can not work: `@import "npm://brand-colors/path-to-less-file"`

**Comment by seven-phases-max** [comment]
Closing as not an issue. (Though it would be an important addition to the docs to mention the plugin looks for `package.json` specified module entry if no explicit file path given).
