### ISSUE TITLE
plugin fails if targeting a file with a .css suffix using gulp-less

### ISSUE THREAD

**Issue by wmyers** [less/less-plugin-npm-import#17]
Using this plugin with gulp-less to embed normalize.css:

In gulp file
```
var LessPluginNPMImport = require('less-plugin-npm-import');
var npmimportless = new LessPluginNPMImport({
    prefix: 'npm://'
  })
...
stream.pipe(less({
    plugins: [npmimportless]
}))
...
```

`normalize.css` dependency contains `normalize.css` file (`/node_modules/normalize.css/normalize.css`)

In less file this fails:
```
@import "npm://normalize.css/normalize.css";
```
Fixed by removing `.css` suffix on the file
```
@import "npm://normalize.css/normalize";
```

**Comment by seven-phases-max** [comment]
>In less file this fails:

How exactly does it fail? Any specific error message? Note that importing a `*.css` file requires [`(css)` option](http://lesscss.org/features/#import-options) (w/o it the statement is supposed to stay as-is to be processed by a browser).

**Comment by wmyers** [comment]
Thanks for response. 

*With* the `.css` the `@import` will stay as-is, *without* the `.css` it will embed it correctly.

Interestingly, if using `(css)` option, it fails to embed (stays as-is) either with or without the `.css`.

So it only works for me *without* the `(css)` option and *without* `.css` suffix.

I'm using node `4.1.2` npm `2.14.4`.

**Comment by seven-phases-max** [comment]
>With the .css the @import will stay as-is, without the .css it will embed it correctly.

Without `css` extension the file is treated like a `less` file and imported accordingly.

>Interestingly, if using (css) option, it fails to embed (stays as-is) either with or without the .css.

My mistake above, sorry (actually you could notice it by reading the docs I pointed to ;). - 
`css` option only stresses the file is `.css` one and the imports stays as is.
To include a .css file you need either `less` or `inline` option (yet again all this is documented at http://lesscss.org/features/#import-directives-feature).

**Comment by wmyers** [comment]
Thanks for clarification, makes sense when reading the less docs :)

Perhaps worth adding a second example lessc usage to your README, before where you say *"css/less extensions not necessary"*

```
@import (less) "npm://packagename/path/to/file.css";
```

**Comment by SomMeri** [comment]
I will close this, since it is not a but and the question is answered. 

@wmyers We will gladly merge in pull request with a new example :). But if you do not have time for it, you can open a new issue in less-docs repo. It will take longer time till someone adds it through in that case.
