### ISSUE TITLE
add less file which is in the node_modules has failed.

### ISSUE THREAD

**Issue by gitdust** [less/less-plugin-npm-import#22]
I tried to import a less file which is [brand-colors](https://github.com/reimertz/brand-colors/)
`@import "npm://brand-colors/path-to-less-file.less";`
error message shows
`Cannot resolve 'file' or 'directory'`

**Comment by seven-phases-max** [comment]
>`@import "npm://brand-colors/path-to-less-file.less";`

Note the `path-to-less-file.less` is just an example file name - it should be your real file name instead.
E.g. for your situation it's `@import "npm://brand-colors/dist/latest/less/brand-colors.latest.less";` (see https://github.com/reimertz/brand-colors/#usage).

**Comment by seven-phases-max** [comment]
Closing as not an issue.

**Comment by gitdust** [comment]
@seven-phases-max My mistake，sorry about that ! I mean the following usage : 
`@import "npm://brand-colors/dist/latest/less/brand-colors.latest.less";`
can not work.
