### ISSUE TITLE
How to use with Grunt?

### ISSUE THREAD

**Issue by MickeyKay** [less/less-plugin-npm-import#23]
Hi there,

Despite my best efforts, I can't seem to get this up and running with my Grunt setup, and I would really appreciate some guidance. At present, I've got my Grunt tasks split out into individual task files within a `/grunt` directory using the `load-grunt-config` plugin: https://github.com/firstandthird/load-grunt-config. So my less compilation task is all defined within `/grunt/less.js`, for example.

How can I integrate `less-plugin-npm-import` into my Grunt setup so that I can include npm `@import` statements in my less files? I've installed the package already, however when I try to run my Grunt build I get `the following:
```
Running "less" (less) task
>> FileError: 'npm://my-npm-package.less' wasn't found in src/less/main.less on line 4, column 1:
```

Clearly I need to formally call/include the task - how can I do this? Thanks!

**Comment by seven-phases-max** [comment]
See https://github.com/gruntjs/grunt-contrib-less#usage-examples
