### ISSUE TITLE
Plugin breaks on require

### ISSUE THREAD

**Issue by dancormier** [less/less-plugin-npm-import#7]
var LessImport = require('less-plugin-npm-import')

This results in `Uncaught TypeError: undefined is not a function` and seems to be due to this statement in "node_modules/resolve/lib/core.js":

    module.exports = require('./core.json').reduce(function (acc, x) {
        acc[x] = true;
        return acc;
    }, {});

**Comment by lukeapage** [comment]
This is another problem in resolve. Either they have published a bad version or you have a problem in your setup.
