### ISSUE TITLE
Requires fs module

### ISSUE THREAD

**Issue by dancormier** [less/less-plugin-npm-import#8]
Upon run, console reads:

    ERROR in ./~/less-plugin-npm-import/~/resolve/lib/async.js
    Module not found: Error: Cannot resolve module 'fs' in /Users/dan/Desktop/test/node_modules/less-plugin-npm-import/node_modules/resolve/lib
     @ ./~/less-plugin-npm-import/~/resolve/lib/async.js 2:9-22

    ERROR in ./~/less-plugin-npm-import/~/resolve/lib/sync.js
    Module not found: Error: Cannot resolve module 'fs' in /Users/dan/Desktop/test/node_modules/less-plugin-npm-import/node_modules/resolve/lib
     @ ./~/less-plugin-npm-import/~/resolve/lib/sync.js 2:9-22

This error is resolved after installing fs with `npm install fs --save`

**Comment by lukeapage** [comment]
The fs module is provided by node.. also the problem is in resolve.. so it is definitely not the right fix to add an fs dep. to this plugin.

**Comment by lukeapage** [comment]
I will try updating dependencies and see if it breaks but i suspect you might have s problem in your node setup.
